runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'fishmyspotcms'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'root'
  INSTANCE_CONNECTION_NAME: 'practicezone:us-central1:fishmyspot'

beta_settings:
  cloud_sql_instances: 'practicezone:us-central1:fishmyspot'
